[workspace]
members = [
  "crates/bin",
  "crates/brontes-core",
  "crates/reth-tracing-ext",
  "crates/brontes-inspect",
  "crates/brontes-types",
  "crates/brontes-classifier",
  "crates/brontes-metrics",
  "crates/brontes-tracing",
  "crates/brontes-database/brontes-db",
  "crates/brontes-macros",
  "crates/brontes-pricing",
  "crates/brontes-database/libmdbx-rs"
]

resolver = "2"

[workspace.dependencies]
# Database
clickhouse = { git = "https://github.com/SorellaLabs/clickhouse.rs", branch = "master", features = [
  "tls",
] }

# Brontes
brontes-core = { path = "./crates/brontes-core" }
brontes-inspect = { path = "./crates/brontes-inspect" }
brontes-types = { path = "./crates/brontes-types/" }
brontes-classifier = { path = "./crates/brontes-classifier/" }
brontes-metrics = { path = "./crates/brontes-metrics/" }
brontes-database = { path = "./crates/brontes-database/brontes-db" }
brontes-macros = { path = "./crates/brontes-macros/" }
brontes-pricing = { path = "./crates/brontes-pricing/" }
reth-tracing-ext = { path = "./crates/reth-tracing-ext/" }
brontes-tracing = { path = "./crates/brontes-tracing" }
brontes-analytics = { path = "./crates/brontes-analytics" }
brontes-libmdbx= { path = "./crates/brontes-database/libmdbx-rs" }

# Reth
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", package = "reth-node-ethereum", version = "1.0.3" }
reth-tasks = { git = "https://github.com/paradigmxyz/reth", package = "reth-tasks", version = "1.0.3" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", package = "reth-chainspec", version = "1.0.3" }
reth-prune-types = { git = "https://github.com/paradigmxyz/reth", package = "reth-prune-types", version = "1.0.3" }
reth-rpc = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc", version = "1.0.3" }
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc-api", version = "1.0.3" }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc-eth-api", version = "1.0.3" }
reth-rpc-eth-types = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc-eth-types", version = "1.0.3" }
reth-rpc-server-types = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc-server-types", version = "1.0.3" }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc-types", version = "1.0.3" }
reth-rpc-builder = { git = "https://github.com/paradigmxyz/reth", package = "reth-rpc-builder", version = "1.0.3" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", package = "reth-provider", version = "1.0.3" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", package = "reth-transaction-pool", version = "1.0.3" }
reth-network-api = { git = "https://github.com/paradigmxyz/reth", package = "reth-network-api", version = "1.0.3" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", package = "reth-primitives", version = "1.0.3" }
reth-db = { git = "https://github.com/paradigmxyz/reth", package = "reth-db", version = "1.0.3" }
reth-db-common = { git = "https://github.com/paradigmxyz/reth", package = "reth-db-common", version = "1.0.3" }
reth-db-api = { git = "https://github.com/paradigmxyz/reth", package = "reth-db-api", version = "1.0.3" }
reth-storage-errors = { git = "https://github.com/paradigmxyz/reth", package = "reth-storage-errors", version = "1.0.3" }
reth-blockchain-tree = { git = "https://github.com/paradigmxyz/reth", package = "reth-blockchain-tree", version = "1.0.3" }
reth-beacon-consensus = { git = "https://github.com/paradigmxyz/reth", package = "reth-beacon-consensus", version = "1.0.3" }
reth-revm = { git = "https://github.com/paradigmxyz/reth", package = "reth-revm", version = "1.0.3" }
reth-stages = { git = "https://github.com/paradigmxyz/reth", package = "reth-stages", features = [
  "test-utils",
], version = "1.0.3" }
reth-trie = { git = "https://github.com/paradigmxyz/reth", package = "reth-trie", version = "1.0.3" }
reth-libmdbx = { git = "https://github.com/paradigmxyz/reth", package = "reth-libmdbx", version = "1.0.3" }
reth-eth-wire = { git = "https://github.com/paradigmxyz/reth", package = "reth-eth-wire", version = "1.0.3" }
reth-payload-builder = { git = "https://github.com/paradigmxyz/reth", package = "reth-payload-builder", version = "1.0.3" }
reth-metrics = { git = "https://github.com/paradigmxyz/reth", package = "reth-metrics", version = "1.0.3" }
reth-codecs = { git = "https://github.com/paradigmxyz/reth", package = "reth-codecs", version = "1.0.3" }
reth-codecs-derive = { git = "https://github.com/paradigmxyz/reth", version = "1.0.3" }
reth-prune-type = { git = "https://github.com/paradigmxyz/reth", package = "prune", version = "1.0.3" }

# ruint
ruint = "1.9.0"

# revm
revm = { version = "12.1.0", features = [
    "std",
    "secp256k1",
    "blst",
], default-features = false }
revm-primitives = { version = "7.1.0", features = [
  "std",
], default-features = false }
revm-inspectors = "0.5"

# Alloy
alloy-rlp = { version = "0.3.4" }
alloy-rlp-derive = { version = "0.3.4" }
alloy-sol-types = { version = "0.7.2", features = ["json"] }
alloy-sol-macro = { version = "0.7.2", features = ["json"] }
alloy-primitives = { version = "0.7.2", features = ["rlp"] }
alloy-json-abi = "0.7.2"
alloy-dyn-abi = "0.7.2"

# Alloy core
alloy-provider = "0.2"
alloy-transport-http = "0.2"
alloy-transport = "0.2"
alloy-network = "0.2"
alloy-json-rpc = "0.2"
alloy-rpc-types = { version = "0.2", features = ["jsonrpsee-types", "eth"] }
alloy-rpc-types-trace = "0.2"
alloy-rpc-client = "0.2"

# Async
tokio = { version = "1.13.0", features = ["full", "tracing"] }
futures = "0.3.28"
async-trait = "0.1.73"

#Tracing
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", default-features = false, features = [
  "env-filter",
  "fmt",
] }
colored = "2.0"

# Metrics
metrics-exporter-prometheus = "=0.12.1"
metrics-util = "0.15.0"
metrics-process = "=1.0.14"

# Logging
env_logger = "0.10.0"

# error handling
thiserror = "1.0.44"
eyre = "0.6.8"

# http/rpc
hyper = "0.14.25"
hyper-tls = "0.5.0"
reqwest = "0.12.2"

# Serde
serde = "1.0.171"
serde_json = "1.0.1"
serde_with = "3.4.0"
serde_repr = "0.1.16"

# cli
clap = { version = "4.4.6", features = ["derive"] }


# Numbers
malachite = "0.4.0"
malachite-q = "0.4.0"

# phf
phf = "0.11.2"
phf_codegen = "0.11.2"

# metrics
metrics = "0.21.1"

# misc
c-kzg = "0.4.0"
hex-literal = "0.4.1"
rayon = "1.7.0"
dotenv = "0.15.0"
semver = "1.0"
lazy_static = "1.4.0"
once_cell = "1.18.0"
itertools = "0.11.0"
parking_lot = "0.12.1"
toml = "0.8.2"
auto_impl = "1.1.0"
strum = "0.25.0"
serial_test = "2.0.0"
derive_more = "0.99.17"
rkyv = { git = "https://github.com/rkyv/rkyv.git", branch = "0.7-hashbrown-0.14", features = [
  "validation",
] }
num_cpus = "1.16.0"
redefined = { git = "https://github.com/SorellaLabs/redefined" }
bytes = "1.5"
bitflags = "2.5.0"

arrow = "51.0.0"
polars = { version = "0.38.3", features = ["lazy"] }
parquet = { version = "51.0.0", features = ["async"] }
indicatif = "0.17.8"

# filesystem
fs2 = "0.4.3"
fs_extra = "1.3.0"
filesize = "0.2.0"
tar = "0.4.41"
flate2 = "1.0.30"


[profile.release]
lto = "thin"
strip = "debuginfo"

[profile.debug-fast]
inherits = "release"
strip = "none"
debug = true


[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1
incremental = false
