[package]
name = "brontes"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
brontes-core.workspace = true
brontes-macros.workspace = true
brontes-inspect.workspace = true
brontes-types.workspace = true
brontes-classifier.workspace = true
brontes-database.workspace = true
brontes-metrics.workspace = true
brontes-pricing.workspace = true
brontes-tracing.workspace = true
brontes-libmdbx = { workspace = true, features = ["read-tx-timeouts"] }

malachite.workspace = true
toml = "0.8.2"
indicatif.workspace = true

# filesystem
fs2.workspace = true
fs_extra.workspace = true
filesize.workspace = true
tar.workspace = true
flate2.workspace = true
directories = "5.0.1"

# Async
tokio = { workspace = true }
async-scoped = { version = "0.7.1", features = ["use-tokio"] }
futures.workspace = true

reqwest.workspace = true
# Reth
reth-tasks.workspace = true
reth-rpc.workspace = true
reth-rpc-api.workspace = true
reth-rpc-types.workspace = true
reth-provider.workspace = true
reth-node-core.workspace = true
reth-transaction-pool.workspace = true
reth-network-api.workspace = true
reth-primitives.workspace = true
reth-db.workspace = true
reth-blockchain-tree.workspace = true
reth-beacon-consensus.workspace = true
#reth-revm.workspace = true
reth-interfaces.workspace = true

# Alloy
alloy-primitives.workspace = true
alloy-sol-macro = { workspace = true, features = ["json"] }
alloy-sol-types = { workspace = true, features = ["json"] }

alloy-provider.workspace = true
alloy-transport-http.workspace = true
alloy-transport.workspace = true
alloy-network.workspace = true
alloy-json-rpc.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-client.workspace = true

# tracing
tracing.workspace = true
tracing-subscriber.workspace = true
reth-tracing-ext.workspace = true
colored.workspace = true

# misc
eyre.workspace = true
dotenv.workspace = true
num_cpus.workspace = true
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true
human_bytes = "0.4.1"
boyer-moore-magiclen = "0.2.16"
comfy-table = "7.0"
serde_json.workspace = true

# http/rpc
hyper.workspace = true

# cli
clap.workspace = true

# logging
rayon.workspace = true
cfg-if = "1.0.0"

# prometheus
metrics-process.workspace = true
prometheus = "0.13.4"
itertools.workspace = true
fdlimit = "0.3.0"
dhat = "0.3.3"

serde = { workspace = true, features = ["derive"] }
db-interfaces = { git = "https://github.com/SorellaLabs/db-interfaces", features = [
  "test-utils",
] }
clickhouse.workspace = true

#TODO: add feature flags for tui
#tui 
crossterm = { version = "0.27", features = ["event-stream", "serde"] }
ratatui = { version = "0.26.1", features = ["all-widgets"] }
palette = "0.7.3"
lazy_static = "1.4.0"
tui-textarea = "0.4.0"
tui-logger = {version = "0.11", features = ["tracing","tracing-support"]}
tui-nodes = "0.3.1"
tracing-log = "0.2.0"
log = "0.4"
config = "0.14.0"
strip-ansi-escapes = "0.2.0"
json5 = "0.4.1"
libc = "0.2.148"
better-panic = "0.3.0"
signal-hook = "0.3.17"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
color-eyre = "0.6.2"
derive_deref = "1.1.1"
tokio-util = "0.7.9"
tracing-error = "0.2.0"
directories = "5.0.1"
ansi-to-tui = "4.0.0"
throbber-widgets-tui= "0.5.0"
unicode-width = "0.1.11"
#console-subscriber = "0.1"


[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.5.4"

[features]
default = [
  "brontes-core/default",
  "brontes-database/default",
  "brontes-classifier/default",
  "brontes-inspect/default",
  "pretty-print",
]

prettytable-rs = "0.10"

# banner
indoc = "2"
crossterm = "0.27.0"
regex = "1.10.4"
rand = "0.8.5"
ansi_term = "0.12.1"
ansi-parser = "0.9.0"
ahash = "0.8.11"

tikv-jemallocator = { version = "0.5.0", features = [
  "unprefixed_malloc_on_supported_platforms",
] }

[features]
default = ["brontes-core/default", "brontes-classifier/default", "jemalloc"]

jemalloc = ["brontes-metrics/jemalloc"]
jemalloc-prof = ["jemalloc", "tikv-jemallocator/profiling"]
dhat-heap = []

sorella-server = ["local-reth", "local-clickhouse"]

tests = [
  "brontes-core/tests",
  "brontes-database/tests",
  "brontes-classifier/tests",
  "brontes-inspect/tests",
  "brontes-pricing/tests",
]

local-reth = [
  "brontes-core/local-reth",
  "brontes-database/local-reth",
  "brontes-types/local-reth",
  "brontes-pricing/local-reth",
  "brontes-inspect/local-reth",
  "reth-tracing-ext/local-reth",
]

local-clickhouse = [
  "brontes-database/local-clickhouse",
  "brontes-core/local-clickhouse",
  "brontes-inspect/local-clickhouse",
  "brontes-classifier/local-clickhouse",
  "brontes-types/local-clickhouse",
]

uni-v3-ticks = ["brontes-pricing/uni-v3-ticks"]
dyn-decode = ["brontes-core/dyn-decode"]
